ntfs_end_buffer_async_read -> post_read_mst_fixup
ntfs_end_buffer_async_read -> post_read_mst_fixup
ntfs_read_block -> vcn_to_lcn
ntfs_read_block -> map_run_list
ntfs_read_block -> vcn_to_lcn
ntfs_read_block -> ntfs_end_buffer_async_read
ntfs_readpage -> ntfs_read_compressed_block
ntfs_readpage -> ntfs_read_block
ntfs_readpage -> map_mft_record
ntfs_readpage -> get_attr_search_ctx
ntfs_readpage -> lookup_attr
ntfs_readpage -> put_attr_search_ctx
ntfs_readpage -> unmap_mft_record
ntfs_rl_realloc -> ntfs_malloc_nofs
ntfs_rl_realloc -> ntfs_free
ntfs_rl_merge -> ntfs_are_rl_mergeable
ntfs_rl_merge -> __ntfs_rl_merge
ntfs_rl_append -> ntfs_are_rl_mergeable
ntfs_rl_append -> ntfs_rl_realloc
ntfs_rl_append -> __ntfs_rl_merge
ntfs_rl_append -> ntfs_rl_mm
ntfs_rl_append -> ntfs_rl_mc
ntfs_rl_insert -> ntfs_are_rl_mergeable
ntfs_rl_insert -> ntfs_rl_realloc
ntfs_rl_insert -> __ntfs_rl_merge
ntfs_rl_insert -> ntfs_rl_mm
ntfs_rl_insert -> ntfs_rl_mc
ntfs_rl_replace -> ntfs_are_rl_mergeable
ntfs_rl_replace -> ntfs_are_rl_mergeable
ntfs_rl_replace -> ntfs_rl_realloc
ntfs_rl_replace -> __ntfs_rl_merge
ntfs_rl_replace -> __ntfs_rl_merge
ntfs_rl_replace -> ntfs_rl_mm
ntfs_rl_replace -> ntfs_rl_mc
ntfs_rl_split -> ntfs_rl_realloc
ntfs_rl_split -> ntfs_rl_mm
ntfs_rl_split -> ntfs_rl_mc
ntfs_merge_run_lists -> ntfs_debug_dump_runlist
ntfs_merge_run_lists -> ntfs_debug_dump_runlist
ntfs_merge_run_lists -> ntfs_rl_realloc
ntfs_merge_run_lists -> ntfs_rl_mm
ntfs_merge_run_lists -> ntfs_rl_replace
ntfs_merge_run_lists -> ntfs_rl_insert
ntfs_merge_run_lists -> ntfs_rl_append
ntfs_merge_run_lists -> ntfs_rl_split
ntfs_merge_run_lists -> ntfs_free
ntfs_merge_run_lists -> ntfs_rl_realloc
ntfs_merge_run_lists -> ntfs_rl_realloc
ntfs_merge_run_lists -> ntfs_debug_dump_runlist
decompress_mapping_pairs -> ntfs_malloc_nofs
decompress_mapping_pairs -> ntfs_malloc_nofs
decompress_mapping_pairs -> ntfs_free
decompress_mapping_pairs -> ntfs_free
decompress_mapping_pairs -> ntfs_debug_dump_runlist
decompress_mapping_pairs -> ntfs_merge_run_lists
decompress_mapping_pairs -> ntfs_free
decompress_mapping_pairs -> ntfs_free
map_run_list -> map_mft_record
map_run_list -> get_attr_search_ctx
map_run_list -> lookup_attr
map_run_list -> put_attr_search_ctx
map_run_list -> vcn_to_lcn
map_run_list -> decompress_mapping_pairs
map_run_list -> put_attr_search_ctx
map_run_list -> unmap_mft_record
find_attr -> ntfs_are_names_equal
find_attr -> ntfs_collate_names
find_attr -> ntfs_collate_names
load_attribute_list -> vcn_to_lcn
load_attribute_list -> vcn_to_lcn
find_external_attr -> ntfs_are_names_equal
find_external_attr -> ntfs_collate_names
find_external_attr -> ntfs_collate_names
find_external_attr -> ntfs_are_names_equal
find_external_attr -> unmap_extent_mft_record
find_external_attr -> map_extent_mft_record
find_external_attr -> ntfs_are_names_equal
find_external_attr -> unmap_extent_mft_record
find_external_attr -> reinit_attr_search_ctx
find_external_attr -> find_attr
lookup_attr -> find_attr
lookup_attr -> find_external_attr
reinit_attr_search_ctx -> unmap_mft_record
reinit_attr_search_ctx -> init_attr_search_ctx
get_attr_search_ctx -> init_attr_search_ctx
put_attr_search_ctx -> unmap_mft_record
ntfs_read_compressed_block -> vcn_to_lcn
ntfs_read_compressed_block -> map_run_list
ntfs_read_compressed_block -> ntfs_decompress
ntfs_read_compressed_block -> ntfs_decompress
ntfs_read_compressed_block -> map_run_list
ntfs_read_compressed_block -> vcn_to_lcn
ntfs_lookup_inode_by_name -> map_mft_record
ntfs_lookup_inode_by_name -> get_attr_search_ctx
ntfs_lookup_inode_by_name -> lookup_attr
ntfs_lookup_inode_by_name -> ntfs_are_names_equal
ntfs_lookup_inode_by_name -> put_attr_search_ctx
ntfs_lookup_inode_by_name -> unmap_mft_record
ntfs_lookup_inode_by_name -> ntfs_are_names_equal
ntfs_lookup_inode_by_name -> ntfs_collate_names
ntfs_lookup_inode_by_name -> ntfs_collate_names
ntfs_lookup_inode_by_name -> put_attr_search_ctx
ntfs_lookup_inode_by_name -> unmap_mft_record
ntfs_lookup_inode_by_name -> ntfs_map_page
ntfs_lookup_inode_by_name -> ntfs_are_names_equal
ntfs_lookup_inode_by_name -> ntfs_unmap_page
ntfs_lookup_inode_by_name -> put_attr_search_ctx
ntfs_lookup_inode_by_name -> unmap_mft_record
ntfs_lookup_inode_by_name -> ntfs_are_names_equal
ntfs_lookup_inode_by_name -> ntfs_unmap_page
ntfs_lookup_inode_by_name -> ntfs_collate_names
ntfs_lookup_inode_by_name -> ntfs_collate_names
ntfs_lookup_inode_by_name -> ntfs_unmap_page
ntfs_lookup_inode_by_name -> ntfs_unmap_page
ntfs_lookup_inode_by_name -> put_attr_search_ctx
ntfs_lookup_inode_by_name -> unmap_mft_record
ntfs_lookup_inode_by_name -> ntfs_unmap_page
ntfs_lookup_inode_by_name -> put_attr_search_ctx
ntfs_lookup_inode_by_name -> unmap_mft_record
ntfs_lookup_inode_by_name -> map_mft_record
ntfs_lookup_inode_by_name -> map_mft_record
ntfs_lookup_inode_by_name -> get_attr_search_ctx
ntfs_lookup_inode_by_name -> lookup_attr
ntfs_lookup_inode_by_name -> ntfs_are_names_equal
ntfs_lookup_inode_by_name -> put_attr_search_ctx
ntfs_lookup_inode_by_name -> unmap_mft_record
ntfs_lookup_inode_by_name -> ntfs_collate_names
ntfs_lookup_inode_by_name -> ntfs_collate_names
ntfs_lookup_inode_by_name -> ntfs_map_page
ntfs_lookup_inode_by_name -> ntfs_are_names_equal
ntfs_lookup_inode_by_name -> ntfs_unmap_page
ntfs_lookup_inode_by_name -> put_attr_search_ctx
ntfs_lookup_inode_by_name -> unmap_mft_record
ntfs_lookup_inode_by_name -> ntfs_collate_names
ntfs_lookup_inode_by_name -> ntfs_collate_names
ntfs_lookup_inode_by_name -> ntfs_unmap_page
ntfs_lookup_inode_by_name -> ntfs_unmap_page
ntfs_lookup_inode_by_name -> put_attr_search_ctx
ntfs_lookup_inode_by_name -> unmap_mft_record
ntfs_lookup_inode_by_name -> map_mft_record
ntfs_filldir -> ntfs_ucstonls
ntfs_readdir -> map_mft_record
ntfs_readdir -> get_attr_search_ctx
ntfs_readdir -> lookup_attr
ntfs_readdir -> ntfs_filldir
ntfs_readdir -> ntfs_attr_iget
ntfs_readdir -> ntfs_map_page
ntfs_readdir -> ntfs_unmap_page
ntfs_readdir -> ntfs_unmap_page
ntfs_readdir -> ntfs_map_page
ntfs_readdir -> ntfs_filldir
ntfs_readdir -> ntfs_unmap_page
ntfs_readdir -> ntfs_unmap_page
ntfs_readdir -> ntfs_unmap_page
ntfs_readdir -> ntfs_unmap_page
ntfs_readdir -> put_attr_search_ctx
ntfs_readdir -> unmap_mft_record
ntfs_readdir -> ntfs_unmap_page
ntfs_readdir -> ntfs_unmap_page
ntfs_readdir -> put_attr_search_ctx
ntfs_readdir -> unmap_mft_record
ntfs_map_page -> ntfs_unmap_page
unmap_extent_mft_record -> unmap_mft_record
ntfs_iget -> ntfs_read_locked_inode
ntfs_attr_iget -> ntfs_read_locked_attr_inode
__ntfs_init_inode -> init_run_list
__ntfs_init_inode -> init_run_list
ntfs_init_big_inode -> __ntfs_init_inode
ntfs_new_extent_inode -> ntfs_alloc_extent_inode
ntfs_new_extent_inode -> __ntfs_init_inode
ntfs_is_extended_system_file -> reinit_attr_search_ctx
ntfs_is_extended_system_file -> lookup_attr
ntfs_read_locked_inode -> ntfs_init_big_inode
ntfs_read_locked_inode -> map_mft_record
ntfs_read_locked_inode -> get_attr_search_ctx
ntfs_read_locked_inode -> lookup_attr
ntfs_read_locked_inode -> ntfs2utc
ntfs_read_locked_inode -> ntfs2utc
ntfs_read_locked_inode -> ntfs2utc
ntfs_read_locked_inode -> reinit_attr_search_ctx
ntfs_read_locked_inode -> lookup_attr
ntfs_read_locked_inode -> attribute_value_length
ntfs_read_locked_inode -> ntfs_malloc_nofs
ntfs_read_locked_inode -> decompress_mapping_pairs
ntfs_read_locked_inode -> load_attribute_list
ntfs_read_locked_inode -> reinit_attr_search_ctx
ntfs_read_locked_inode -> lookup_attr
ntfs_read_locked_inode -> reinit_attr_search_ctx
ntfs_read_locked_inode -> lookup_attr
ntfs_read_locked_inode -> ntfs_attr_iget
ntfs_read_locked_inode -> reinit_attr_search_ctx
ntfs_read_locked_inode -> lookup_attr
ntfs_read_locked_inode -> ntfs_is_extended_system_file
ntfs_read_locked_inode -> put_attr_search_ctx
ntfs_read_locked_inode -> unmap_mft_record
ntfs_read_locked_inode -> put_attr_search_ctx
ntfs_read_locked_inode -> unmap_mft_record
ntfs_read_locked_attr_inode -> ntfs_init_big_inode
ntfs_read_locked_attr_inode -> map_mft_record
ntfs_read_locked_attr_inode -> get_attr_search_ctx
ntfs_read_locked_attr_inode -> lookup_attr
ntfs_read_locked_attr_inode -> put_attr_search_ctx
ntfs_read_locked_attr_inode -> unmap_mft_record
ntfs_read_locked_attr_inode -> put_attr_search_ctx
ntfs_read_locked_attr_inode -> unmap_mft_record
ntfs_read_inode_mount -> ntfs_init_big_inode
ntfs_read_inode_mount -> ntfs_malloc_nofs
ntfs_read_inode_mount -> post_read_mst_fixup
ntfs_read_inode_mount -> get_attr_search_ctx
ntfs_read_inode_mount -> lookup_attr
ntfs_read_inode_mount -> attribute_value_length
ntfs_read_inode_mount -> ntfs_malloc_nofs
ntfs_read_inode_mount -> decompress_mapping_pairs
ntfs_read_inode_mount -> load_attribute_list
ntfs_read_inode_mount -> reinit_attr_search_ctx
ntfs_read_inode_mount -> lookup_attr
ntfs_read_inode_mount -> decompress_mapping_pairs
ntfs_read_inode_mount -> decompress_mapping_pairs
ntfs_read_inode_mount -> ntfs_read_locked_inode
ntfs_read_inode_mount -> put_attr_search_ctx
ntfs_read_inode_mount -> put_attr_search_ctx
ntfs_read_inode_mount -> ntfs_free
ntfs_read_inode_mount -> put_attr_search_ctx
__ntfs_clear_inode -> ntfs_commit_inode
__ntfs_clear_inode -> ntfs_clear_extent_inode
__ntfs_clear_inode -> ntfs_free
__ntfs_clear_inode -> ntfs_free
__ntfs_clear_inode -> ntfs_free
ntfs_clear_extent_inode -> __ntfs_clear_inode
ntfs_clear_extent_inode -> ntfs_destroy_extent_inode
ntfs_clear_big_inode -> __ntfs_clear_inode
format_mft_record -> map_mft_record
format_mft_record -> __format_mft_record
format_mft_record -> unmap_mft_record
map_mft_record_page -> ntfs_map_page
unmap_mft_record_page -> ntfs_unmap_page
map_mft_record -> map_mft_record_page
unmap_mft_record -> unmap_mft_record_page
map_extent_mft_record -> map_mft_record
map_extent_mft_record -> unmap_mft_record
map_extent_mft_record -> ntfs_new_extent_inode
map_extent_mft_record -> map_mft_record
map_extent_mft_record -> ntfs_clear_extent_inode
map_extent_mft_record -> unmap_mft_record
map_extent_mft_record -> ntfs_clear_extent_inode
ntfs_lookup -> ntfs_nlstoucs
ntfs_lookup -> ntfs_iget
ntfs_lookup -> ntfs_iget
ntfs_lookup -> ntfs_ucstonls
ntfs_lookup -> map_mft_record
ntfs_lookup -> get_attr_search_ctx
ntfs_lookup -> lookup_attr
ntfs_lookup -> ntfs_ucstonls
ntfs_lookup -> put_attr_search_ctx
ntfs_lookup -> unmap_mft_record
ntfs_lookup -> put_attr_search_ctx
ntfs_lookup -> unmap_mft_record
parse_options -> simple_getbool
parse_options -> simple_getbool
ntfs_remount -> parse_options
read_ntfs_boot_sector -> is_boot_sector_ntfs
read_ntfs_boot_sector -> is_boot_sector_ntfs
read_ntfs_boot_sector -> is_boot_sector_ntfs
load_and_init_upcase -> ntfs_iget
load_and_init_upcase -> ntfs_malloc_nofs
load_and_init_upcase -> ntfs_map_page
load_and_init_upcase -> ntfs_unmap_page
load_and_init_upcase -> ntfs_free
load_and_init_upcase -> ntfs_free
load_system_files -> ntfs_attr_iget
load_system_files -> ntfs_iget
load_system_files -> load_and_init_upcase
load_system_files -> ntfs_iget
load_system_files -> ntfs_iget
load_system_files -> lookup_attr
load_system_files -> put_attr_search_ctx
load_system_files -> put_attr_search_ctx
load_system_files -> ntfs_iget
load_system_files -> ntfs_iget
load_system_files -> ntfs_iget
load_system_files -> ntfs_iget
load_system_files -> ntfs_iget
ntfs_put_super -> ntfs_free
ntfs_put_super -> free_compression_buffers
ntfs_put_super -> ntfs_free
__get_nr_free_mft_records -> ntfs_map_page
__get_nr_free_mft_records -> ntfs_map_page
__get_nr_free_mft_records -> ntfs_unmap_page
ntfs_statfs -> get_nr_free_clusters
ntfs_statfs -> __get_nr_free_mft_records
ntfs_fill_super -> parse_options
ntfs_fill_super -> read_ntfs_boot_sector
ntfs_fill_super -> parse_ntfs_boot_sector
ntfs_fill_super -> ntfs_read_inode_mount
ntfs_fill_super -> allocate_compression_buffers
ntfs_fill_super -> generate_default_upcase
ntfs_fill_super -> load_system_files
ntfs_fill_super -> ntfs_free
ntfs_fill_super -> ntfs_free
ntfs_fill_super -> ntfs_free
ntfs_fill_super -> free_compression_buffers
init_ntfs_fs -> ntfs_sysctl
exit_ntfs_fs -> ntfs_sysctl
get_current_ntfs_time -> utc2ntfs
ntfs_are_names_equal -> ntfs_ucsncmp
ntfs_are_names_equal -> ntfs_ucsncasecmp
ntfs_file_upcase_value -> ntfs_upcase_name
ntfs_file_compare_values -> ntfs_collate_names
generate_default_upcase -> ntfs_malloc_nofs
